In [1]:
import pandas as pd
import networkx as nx

edges = pd.read_csv("data/processed/edges_snowball_core.csv")

In [2]:
edges

                player_a              player_b  n_games  distance
0               adacinar              anuveera        4  0.250000
1               adacinar  constantinlaurentiu1        1  1.000000
2               adacinar             erasercyb        1  1.000000
3               adacinar           james555000        1  1.000000
4                   aday              altair39        4  0.250000
...                  ...                   ...      ...       ...
1062          yoseph2013             yyoochess        2  0.500000
1063          yoseph2013       zhigalko_sergei        4  0.250000
1064           yyoochess       zhigalko_sergei        1  1.000000
1065  zashibeatles_chess                  zkid        3  0.333333
1066     zaven_chessmood       zhigalko_sergei        1  1.000000

[1067 rows x 4 columns]

In [3]:
players = pd.read_csv("data/processed/players_snowball.csv").set_index("username")
players

,is_snowball,n_games,win_rate,draw_rate,avg_moves,share_bullet,share_blitz,share_rapid,share_classical,account_age_days,...,rating,opponents_per_game,opening_diversity,target_growth_games,target_growth_1m,target_growth_1m_top20,target_growth_3m,target_growth_3m_top20,target_growth_6m,target_growth_6m_top20
username,,,,,,,,,,,,,,,,,,,,,
aday,False,50,0.580000,0.080000,36.370000,0.040000,0.960000,0.000000,0.0,3878,...,1708,0.760000,3.178692,62,83.0,1.0,168.0,1.0,239.0,1.0
aguilerasmiguel,False,50,0.460000,0.080000,37.360000,0.060000,0.940000,0.000000,0.0,3095,...,1684,0.920000,3.705142,-9,-2.0,0.0,-2.0,0.0,-2.0,0.0
ahmedhosny12,False,51,0.313725,0.019608,36.931373,0.588235,0.392157,0.019608,0.0,2433,...,1515,0.980392,3.430939,-61,-102.0,0.0,-102.0,0.0,-102.0,0.0
alaykiss,False,51,0.392157,0.039216,42.519608,0.000000,1.000000,0.000000,0.0,1801,...,1666,0.352941,3.442597,60,-5.0,0.0,27.0,0.0,40.0,0.0
alex-31,False,54,0.592593,0.037037,35.222222,0.259259,0.740741,0.000000,0.0,1177,...,2412,0.814815,3.402559,-48,-1.0,0.0,-48.0,0.0,39.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
yoseph2013,True,50,0.720000,0.080000,39.830000,0.000000,1.000000,0.000000,0.0,3594,...,2723,0.740000,3.632306,-10,-74.0,0.0,50.0,0.0,74.0,0.0
zashibeatles_chess,True,50,0.320000,0.120000,50.510000,0.980000,0.020000,0.000000,0.0,1541,...,2940,0.360000,4.132504,-67,91.0,1.0,58.0,0.0,95.0,1.0
zigzagbb,True,50,0.480000,0.040000,46.040000,1.000000,0.000000,0.000000,0.0,1567,...,2940,0.280000,3.677082,17,2.0,0.0,-1.0,0.0,26.0,0.0
zkid,True,50,0.680000,0.100000,42.570000,0.000000,1.000000,0.000000,0.0,3065,...,2886,0.620000,3.393270,-24,10.0,0.0,19.0,0.0,66.0,0.0
zlatoustintergaming,True,50,0.680000,0.080000,42.060000,1.000000,0.000000,0.000000,0.0,440,...,3110,0.340000,3.747363,2,71.0,1.0,132.0,1.0,184.0,1.0

In [4]:
graph = nx.Graph()
graph.add_nodes_from(players.index)
for row in edges.itertuples():
    graph.add_edge(row.player_a, row.player_b, weight=row.distance)

In [5]:
lu = players.copy()

categorical_cols = ['title', 'main_tc']
columns_to_ignore = [
    'target_growth_games', 'target_growth_1m', 'target_growth_1m_top20', 'target_growth_3m', 'target_growth_3m_top20', 
    'target_growth_6m', 'target_growth_6m_top20', 'rating', 'username']


for col in lu.columns:
    if col not in categorical_cols + columns_to_ignore:
        lu[col] = lu[col].astype(float)

In [6]:
lu

,is_snowball,n_games,win_rate,draw_rate,avg_moves,share_bullet,share_blitz,share_rapid,share_classical,account_age_days,...,rating,opponents_per_game,opening_diversity,target_growth_games,target_growth_1m,target_growth_1m_top20,target_growth_3m,target_growth_3m_top20,target_growth_6m,target_growth_6m_top20
username,,,,,,,,,,,,,,,,,,,,,
aday,0.0,50.0,0.580000,0.080000,36.370000,0.040000,0.960000,0.000000,0.0,3878.0,...,1708,0.760000,3.178692,62,83.0,1.0,168.0,1.0,239.0,1.0
aguilerasmiguel,0.0,50.0,0.460000,0.080000,37.360000,0.060000,0.940000,0.000000,0.0,3095.0,...,1684,0.920000,3.705142,-9,-2.0,0.0,-2.0,0.0,-2.0,0.0
ahmedhosny12,0.0,51.0,0.313725,0.019608,36.931373,0.588235,0.392157,0.019608,0.0,2433.0,...,1515,0.980392,3.430939,-61,-102.0,0.0,-102.0,0.0,-102.0,0.0
alaykiss,0.0,51.0,0.392157,0.039216,42.519608,0.000000,1.000000,0.000000,0.0,1801.0,...,1666,0.352941,3.442597,60,-5.0,0.0,27.0,0.0,40.0,0.0
alex-31,0.0,54.0,0.592593,0.037037,35.222222,0.259259,0.740741,0.000000,0.0,1177.0,...,2412,0.814815,3.402559,-48,-1.0,0.0,-48.0,0.0,39.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
yoseph2013,1.0,50.0,0.720000,0.080000,39.830000,0.000000,1.000000,0.000000,0.0,3594.0,...,2723,0.740000,3.632306,-10,-74.0,0.0,50.0,0.0,74.0,0.0
zashibeatles_chess,1.0,50.0,0.320000,0.120000,50.510000,0.980000,0.020000,0.000000,0.0,1541.0,...,2940,0.360000,4.132504,-67,91.0,1.0,58.0,0.0,95.0,1.0
zigzagbb,1.0,50.0,0.480000,0.040000,46.040000,1.000000,0.000000,0.000000,0.0,1567.0,...,2940,0.280000,3.677082,17,2.0,0.0,-1.0,0.0,26.0,0.0
zkid,1.0,50.0,0.680000,0.100000,42.570000,0.000000,1.000000,0.000000,0.0,3065.0,...,2886,0.620000,3.393270,-24,10.0,0.0,19.0,0.0,66.0,0.0
zlatoustintergaming,1.0,50.0,0.680000,0.080000,42.060000,1.000000,0.000000,0.000000,0.0,440.0,...,3110,0.340000,3.747363,2,71.0,1.0,132.0,1.0,184.0,1.0

In [7]:
import sys
from pathlib import Path

project_root = Path.cwd().parent 
sys.path.insert(0, str(project_root))

from algorithm.methods import ranking, significance_test, find_groups

result = find_groups(
    graph, 20, lu, 
    'target_growth_games', 
    columns_to_ignore, 
    categorical_cols, ablation_mode=False, use_multiprocessing=False)

100%|██████████| 346/346 [04:15<00:00,  1.35it/s]

In [8]:
result

,rho,sigma,q,ranks,reference,subgroup
node,,,,,,
amin_____tb,48,3,1.505301,"[(amin_____tb, -49), (metiforce, -56), (topgra...","[amin_____tb, metiforce, topgrandmaster, tamoj...","[amin_____tb, metiforce, topgrandmaster]"
sadullo_azizov1,50,4,1.424131,"[(sadullo_azizov1, -24), (herzog2012, -15), (z...","[sadullo_azizov1, herzog2012, zaven_chessmood,...","[sadullo_azizov1, herzog2012, zaven_chessmood,..."
rhizocarpon,51,6,1.408364,"[(rhizocarpon, -6), (nihalsarin, 40), (eloof, ...","[rhizocarpon, nihalsarin, eloof, kava69, palom...","[rhizocarpon, nihalsarin, eloof, kava69, palom..."
untilitisotherwise,23,3,1.345748,"[(untilitisotherwise, -97), (matviy2009, -410)...","[untilitisotherwise, matviy2009, secret_magnus...","[untilitisotherwise, matviy2009, secret_magnus]"
mutdpro,21,4,1.309307,"[(mutdpro, -152), (alireza2003, -35), (rebecca...","[mutdpro, alireza2003, rebeccaharris, bigal1, ...","[mutdpro, alireza2003, rebeccaharris, bigal1]"
viktor0008,72,3,1.272792,"[(viktor0008, -67), (asdaasda55, -19), (eucaly...","[viktor0008, asdaasda55, eucalyptus_tree, joed...","[viktor0008, asdaasda55, eucalyptus_tree]"
zkid,39,4,1.220966,"[(zkid, -24), (zashibeatles_chess, -67), (hitt...","[zkid, zashibeatles_chess, hitter1999, metifor...","[zkid, zashibeatles_chess, hitter1999, metiforce]"
antoniosafar,55,4,1.193718,"[(antoniosafar, -3), (sajjadjafarinezhad2, 21)...","[antoniosafar, sajjadjafarinezhad2, nihalsarin...","[antoniosafar, sajjadjafarinezhad2, nihalsarin..."
topgrandmaster,16,3,1.192079,"[(topgrandmaster, -88), (metiforce, -56), (ami...","[topgrandmaster, metiforce, amin_____tb, zkid,...","[topgrandmaster, metiforce, amin_____tb]"
zigzagbb,47,13,1.190799,"[(zigzagbb, 17), (bardiya___daneshvar, -11), (...","[zigzagbb, bardiya___daneshvar, tamojerry, ala...","[zigzagbb, bardiya___daneshvar, tamojerry, ala..."
arturopl,38,3,1.184788,"[(arturopl, 7), (ali681493, 5), (nihalsarin, 4...","[arturopl, ali681493, nihalsarin, cesararturo2...","[arturopl, ali681493, nihalsarin]"
prithvirajprajeesh,29,12,1.180423,"[(prithvirajprajeesh, -48), (bardiya___daneshv...","[prithvirajprajeesh, bardiya___daneshvar, tamo...","[prithvirajprajeesh, bardiya___daneshvar, tamo..."
timaina1,40,6,1.180150,"[(timaina1, -31), (rd-2, 30), (hripach007, 7),...","[timaina1, rd-2, hripach007, mikele84, skilled...","[timaina1, rd-2, hripach007, mikele84, skilled..."
wizard98,24,4,1.157275,"[(wizard98, -7), (mishka_the_great, -33), (gah...","[wizard98, mishka_the_great, gahan-mg, yoseph2...","[wizard98, mishka_the_great, gahan-mg, yoseph2..."
adacinar,22,9,1.148759,"[(adacinar, 20), (anuveera, -34), (james555000...","[adacinar, anuveera, james555000, constantinla...","[adacinar, anuveera, james555000, constantinla..."
mats1980,43,5,1.132030,"[(mats1980, -9), (manoj22579, -8), (bjh095, 12...","[mats1980, manoj22579, bjh095, vladislaw69, ni...","[mats1980, manoj22579, bjh095, vladislaw69, ni..."
badalzadeh60,17,3,1.127204,"[(badalzadeh60, 134), (alaykiss, 60), (tubbytu...","[badalzadeh60, alaykiss, tubbytubtub, stale2, ...","[badalzadeh60, alaykiss, tubbytubtub]"
dr_tiger,18,7,1.122497,"[(dr_tiger, 16), (kostik_mostik, -27), (chessm...","[dr_tiger, kostik_mostik, chessmaster2006, kon...","[dr_tiger, kostik_mostik, chessmaster2006, kon..."
crecent,11,3,1.116581,"[(crecent, -9), (gahan-mg, -10), (bardiya___da...","[crecent, gahan-mg, bardiya___daneshvar, smihi...","[crecent, gahan-mg, bardiya___daneshvar]"
bh_totoro,99,3,1.103120,"[(bh_totoro, -12), (chris04re, -23), (selcukya...","[bh_totoro, chris04re, selcukyasinunsal, jvksp...","[bh_totoro, chris04re, selcukyasinunsal]"

In [25]:
reference = result.iloc[0]['reference']
subgroup = result.iloc[0]['subgroup']

print("Avg target of the reference: ", lu.loc[lu.index.isin(reference), 'target_growth_games'].mean())
print("Avg target of the subgroup: ", lu.loc[lu.index.isin(subgroup), 'target_growth_games'].mean())

Avg target of the reference:  11.020833333333334
Avg target of the subgroup:  -64.33333333333333

In [26]:
reference = result.iloc[1]['reference']
subgroup = result.iloc[1]['subgroup']

print("Avg target of the reference: ", lu.loc[lu.index.isin(reference), 'target_growth_games'].mean())
print("Avg target of the subgroup: ", lu.loc[lu.index.isin(subgroup), 'target_growth_games'].mean())

Avg target of the reference:  10.18
Avg target of the subgroup:  -51.25

In [27]:
reference = result.iloc[2]['reference']
subgroup = result.iloc[2]['subgroup']

print("Avg target of the reference: ", lu.loc[lu.index.isin(reference), 'target_growth_games'].mean())
print("Avg target of the subgroup: ", lu.loc[lu.index.isin(subgroup), 'target_growth_games'].mean())

Avg target of the reference:  -16.745098039215687
Avg target of the subgroup:  36.166666666666664

In [28]:
reference = result.iloc[3]['reference']
subgroup = result.iloc[3]['subgroup']

print("Avg target of the reference: ", lu.loc[lu.index.isin(reference), 'target_growth_games'].mean())
print("Avg target of the subgroup: ", lu.loc[lu.index.isin(subgroup), 'target_growth_games'].mean())

Avg target of the reference:  0.6086956521739131
Avg target of the subgroup:  -185.66666666666666