## Issue 1: Gower tie-breaker treats categorical targets as numerical

In [1]:
import pickle
import pandas as pd
import networkx as nx
import pickle as pkl
import matplotlib.pyplot as plt


# Open the pickle file in binary read mode ('rb')
with open('graph_349519_OGBG.pkl', 'rb') as file:
    data = pickle.load(file)

In [2]:
import sys
from pathlib import Path

project_root = Path.cwd().parent 
sys.path.insert(0, str(project_root))

from algorithm.methods import ranking, significance_test, find_groups

In [3]:
edge_index = data['edge_index']
num_nodes = data['num_nodes']

G = nx.Graph()

G.add_nodes_from(range(num_nodes))

edges = list(zip(edge_index[0], edge_index[1]))
G.add_edges_from(edges)

In [4]:
attributes = data['node_feat']
lu = pd.DataFrame(attributes)
lu['target'] = lu[0] >= 6

In [6]:
result = find_groups(G, 20, lu, [], ["0", "1", "7", "8", "9"], ablation_mode=False, use_multiprocessing=False)

100%|██████████| 332/332 [01:31<00:00,  3.64it/s]

In [7]:
result

,rho,sigma,q,ranks,reference,subgroup
node,,,,,,
46,9,3,0.320750,"[(46, False), (44, False), (47, False), (45, T...","[46, 44, 47, 45, 42, 49, 48, 41, 43]","[46, 44, 47]"
28,14,5,0.230508,"[(28, True), (27, False), (26, True), (29, Fal...","[28, 27, 26, 29, 33, 25, 30, 22, 20, 34, 24, 2...","[28, 27, 26, 29, 33]"
34,13,5,0.228987,"[(34, False), (33, True), (35, True), (36, Fal...","[34, 33, 35, 36, 41, 37, 32, 29, 27, 38, 42, 3...","[34, 33, 35, 36, 41]"
253,13,5,0.228987,"[(253, False), (255, True), (254, True), (247,...","[253, 255, 254, 247, 246, 248, 256, 244, 261, ...","[253, 255, 254, 247, 246]"
147,13,5,0.228987,"[(147, False), (149, True), (148, True), (141,...","[147, 149, 148, 141, 140, 142, 150, 138, 155, ...","[147, 149, 148, 141, 140]"
11,11,7,0.207201,"[(11, True), (12, False), (8, False), (13, Tru...","[11, 12, 8, 13, 6, 9, 14, 5, 19, 7, 10]","[11, 12, 8, 13, 6, 9, 14]"
167,5,3,0.206559,"[(167, True), (168, False), (166, False), (169...","[167, 168, 166, 169, 170]","[167, 168, 166]"
268,5,3,0.206559,"[(268, True), (269, False), (267, False), (270...","[268, 269, 267, 270, 271]","[268, 269, 267]"
45,9,4,0.203704,"[(45, True), (44, False), (46, False), (42, Fa...","[45, 44, 46, 42, 41, 47, 43, 49, 48]","[45, 44, 46, 42]"
272,16,5,0.195656,"[(272, False), (274, True), (273, True), (264,...","[272, 274, 273, 264, 263, 265, 275, 261, 276, ...","[272, 274, 273, 264, 263]"
299,19,11,0.192952,"[(299, False), (301, True), (300, True), (294,...","[299, 301, 300, 294, 293, 295, 302, 291, 296, ...","[299, 301, 300, 294, 293, 295, 302, 291, 296, ..."
180,5,4,0.178885,"[(180, False), (179, False), (181, False), (17...","[180, 179, 181, 178, 182]","[180, 179, 181, 178]"
282,25,10,0.164438,"[(282, True), (280, False), (283, False), (281...","[282, 280, 283, 281, 291, 284, 279, 278, 293, ...","[282, 280, 283, 281, 291, 284, 279, 278, 293, ..."
132,23,10,0.157678,"[(132, True), (130, False), (133, False), (131...","[132, 130, 133, 131, 138, 134, 125, 124, 140, ...","[132, 130, 133, 131, 138, 134, 125, 124, 140, ..."
258,11,6,0.156662,"[(258, False), (257, False), (259, True), (260...","[258, 257, 259, 260, 256, 261, 255, 253, 263, ...","[258, 257, 259, 260, 256, 261]"
296,11,6,0.156662,"[(296, False), (295, False), (297, True), (298...","[296, 295, 297, 298, 294, 299, 293, 291, 301, ...","[296, 295, 297, 298, 294, 299]"
19,22,10,0.153227,"[(19, True), (20, False), (14, False), (21, Tr...","[19, 20, 14, 21, 12, 15, 22, 11, 26, 13, 16, 2...","[19, 20, 14, 21, 12, 15, 22, 11, 26, 13]"
281,30,5,0.149691,"[(281, True), (280, False), (282, True), (279,...","[281, 280, 282, 279, 278, 315, 283, 276, 291, ...","[281, 280, 282, 279, 278]"
21,27,5,0.146631,"[(21, True), (20, False), (19, True), (22, Fal...","[21, 20, 19, 22, 26, 14, 23, 12, 27, 15, 24, 2...","[21, 20, 19, 22, 26]"
130,27,5,0.146631,"[(130, False), (132, True), (131, True), (125,...","[130, 132, 131, 125, 124, 126, 133, 122, 138, ...","[130, 132, 131, 125, 124]"

In [8]:
# original results
pd.read_csv("original_results.csv")

,node,rho,sigma,q,ranks,reference,subgroup
0,46,9,3,0.320750,"[(46, np.False_), (np.int64(44), np.False_), (...","[46, np.int64(44), np.int64(47), np.int64(45),...","[46, np.int64(44), np.int64(47)]"
1,28,14,5,0.230508,"[(28, np.True_), (np.int64(27), np.False_), (n...","[28, np.int64(27), np.int64(26), np.int64(29),...","[28, np.int64(27), np.int64(26), np.int64(29),..."
2,35,13,5,0.228987,"[(35, np.True_), (np.int64(34), np.False_), (n...","[35, np.int64(34), np.int64(33), np.int64(36),...","[35, np.int64(34), np.int64(33), np.int64(36),..."
3,11,11,7,0.207201,"[(11, np.True_), (np.int64(12), np.False_), (n...","[11, np.int64(12), np.int64(8), np.int64(6), n...","[11, np.int64(12), np.int64(8), np.int64(6), n..."
4,253,22,13,0.206959,"[(253, np.False_), (np.int64(255), np.True_), ...","[253, np.int64(255), np.int64(254), np.int64(2...","[253, np.int64(255), np.int64(254), np.int64(2..."
5,268,5,3,0.206559,"[(268, np.True_), (np.int64(269), np.False_), ...","[268, np.int64(269), np.int64(267), np.int64(2...","[268, np.int64(269), np.int64(267)]"
6,167,5,3,0.206559,"[(167, np.True_), (np.int64(168), np.False_), ...","[167, np.int64(168), np.int64(166), np.int64(1...","[167, np.int64(168), np.int64(166)]"
7,300,19,11,0.192952,"[(300, np.True_), (np.int64(299), np.False_), ...","[300, np.int64(299), np.int64(301), np.int64(2...","[300, np.int64(299), np.int64(301), np.int64(2..."
8,180,5,4,0.178885,"[(180, np.False_), (np.int64(179), np.False_),...","[180, np.int64(179), np.int64(181), np.int64(1...","[180, np.int64(179), np.int64(181), np.int64(1..."
9,19,19,10,0.171823,"[(19, np.True_), (np.int64(20), np.False_), (n...","[19, np.int64(20), np.int64(14), np.int64(12),...","[19, np.int64(20), np.int64(14), np.int64(12),..."
10,149,19,10,0.171823,"[(149, np.True_), (np.int64(147), np.False_), ...","[149, np.int64(147), np.int64(150), np.int64(1...","[149, np.int64(147), np.int64(150), np.int64(1..."
11,282,25,10,0.164438,"[(282, np.True_), (np.int64(280), np.False_), ...","[282, np.int64(280), np.int64(283), np.int64(2...","[282, np.int64(280), np.int64(283), np.int64(2..."
12,145,12,7,0.163663,"[(145, np.True_), (np.int64(144), np.False_), ...","[145, np.int64(144), np.int64(146), np.int64(1...","[145, np.int64(144), np.int64(146), np.int64(1..."
13,132,23,10,0.157678,"[(132, np.True_), (np.int64(130), np.False_), ...","[132, np.int64(130), np.int64(133), np.int64(1...","[132, np.int64(130), np.int64(133), np.int64(1..."
14,260,11,6,0.156662,"[(260, np.True_), (np.int64(258), np.False_), ...","[260, np.int64(258), np.int64(259), np.int64(2...","[260, np.int64(258), np.int64(259), np.int64(2..."
15,39,11,6,0.156662,"[(39, np.True_), (np.int64(38), np.False_), (n...","[39, np.int64(38), np.int64(40), np.int64(37),...","[39, np.int64(38), np.int64(40), np.int64(37),..."
16,296,11,6,0.156662,"[(296, np.False_), (np.int64(297), np.True_), ...","[296, np.int64(297), np.int64(298), np.int64(2...","[296, np.int64(297), np.int64(298), np.int64(2..."
17,304,7,3,0.155870,"[(304, np.True_), (np.int64(303), np.False_), ...","[304, np.int64(303), np.int64(302), np.int64(3...","[304, np.int64(303), np.int64(302)]"
18,274,22,10,0.153227,"[(274, np.True_), (np.int64(272), np.False_), ...","[274, np.int64(272), np.int64(275), np.int64(2...","[274, np.int64(272), np.int64(275), np.int64(2..."
19,280,31,5,0.150280,"[(280, np.False_), (np.int64(282), np.True_), ...","[280, np.int64(282), np.int64(281), np.int64(2...","[280, np.int64(282), np.int64(281), np.int64(2..."