## Issue 1: Gower tie-breaker treats categorical targets as numerical

In [1]:
import pickle
import pandas as pd
import networkx as nx
import pickle as pkl
import matplotlib.pyplot as plt


# Open the pickle file in binary read mode ('rb')
with open('graph_349519_OGBG.pkl', 'rb') as file:
    data = pickle.load(file)

In [2]:
import sys
from pathlib import Path

project_root = Path.cwd().parent 
sys.path.insert(0, str(project_root))

from algorithm.methods import ranking, significance_test, find_groups

In [3]:
edge_index = data['edge_index']
num_nodes = data['num_nodes']

G = nx.Graph()

G.add_nodes_from(range(num_nodes))

edges = list(zip(edge_index[0], edge_index[1]))
G.add_edges_from(edges)

In [4]:
attributes = data['node_feat']
lu = pd.DataFrame(attributes)
lu['target'] = lu[0] >= 6

categorical_cols = ["1", "7", "8", "9"]
columns_to_ignore = [0, 'target']

for col in lu.columns:
    if col not in categorical_cols + columns_to_ignore:
        lu[col] = lu[col].astype(float)

In [6]:
result = find_groups(G, 20, lu, 0, columns_to_ignore, categorical_cols, ablation_mode=False, use_multiprocessing=False)

100%|██████████| 332/332 [07:05<00:00,  1.28s/it]

In [7]:
result

,rho,sigma,q,ranks,reference,subgroup
node,,,,,,
285,332,9,1.123429,"[(285, False), (286, False), (290, False), (28...","[285, 286, 290, 284, 287, 289, 283, 288, 291, ...","[285, 286, 290, 284, 287, 289, 283, 288, 291]"
75,332,9,1.123429,"[(75, False), (76, False), (80, False), (74, F...","[75, 76, 80, 74, 77, 79, 73, 78, 81, 72, 70, 8...","[75, 76, 80, 74, 77, 79, 73, 78, 81]"
64,332,5,0.842309,"[(64, False), (63, False), (65, False), (62, F...","[64, 63, 65, 62, 61, 60, 66, 68, 58, 67, 53, 6...","[64, 63, 65, 62, 61]"
126,332,5,0.842309,"[(126, False), (127, False), (125, False), (12...","[126, 127, 125, 128, 129, 124, 130, 132, 122, ...","[126, 127, 125, 128, 129]"
105,332,5,0.842309,"[(105, False), (104, False), (106, False), (10...","[105, 104, 106, 103, 102, 101, 107, 109, 99, 1...","[105, 104, 106, 103, 102]"
316,332,5,0.842309,"[(316, False), (315, False), (317, False), (27...","[316, 315, 317, 279, 318, 278, 280, 282, 276, ...","[316, 315, 317, 279, 318]"
319,332,5,0.842309,"[(319, False), (275, False), (321, False), (32...","[319, 275, 321, 320, 322, 274, 276, 278, 272, ...","[319, 275, 321, 320, 322]"
96,332,5,0.842309,"[(96, False), (95, False), (97, False), (98, F...","[96, 95, 97, 98, 94, 93, 99, 101, 91, 100, 84,...","[96, 95, 97, 98, 94]"
137,332,5,0.842309,"[(137, False), (135, False), (136, False), (13...","[137, 135, 136, 134, 133, 132, 138, 140, 130, ...","[137, 135, 136, 134, 133]"
154,332,5,0.842309,"[(154, False), (152, False), (153, False), (15...","[154, 152, 153, 151, 150, 149, 155, 157, 147, ...","[154, 152, 153, 151, 150]"
0,332,5,0.842309,"[(0, False), (1, False), (2, False), (3, False...","[0, 1, 2, 3, 4, 5, 50, 52, 6, 51, 53, 8, 7, 9,...","[0, 1, 2, 3, 4]"
18,332,5,0.842309,"[(18, False), (16, False), (17, False), (15, F...","[18, 16, 17, 15, 14, 19, 12, 11, 20, 13, 8, 22...","[18, 16, 17, 15, 14]"
112,332,4,0.754505,"[(112, False), (111, False), (113, False), (11...","[112, 111, 113, 110, 114, 109, 118, 115, 117, ...","[112, 111, 113, 110]"
31,332,4,0.754505,"[(31, False), (30, False), (32, False), (29, F...","[31, 30, 32, 29, 33, 27, 34, 26, 36, 28, 35, 2...","[31, 30, 32, 29]"
24,332,4,0.754505,"[(24, False), (23, False), (25, False), (22, F...","[24, 23, 25, 22, 26, 20, 27, 29, 19, 21, 28, 3...","[24, 23, 25, 22]"
266,332,4,0.754505,"[(266, False), (265, False), (267, False), (26...","[266, 265, 267, 264, 268, 263, 272, 269, 271, ...","[266, 265, 267, 264]"
240,332,4,0.754505,"[(240, False), (239, False), (241, False), (23...","[240, 239, 241, 238, 243, 242, 237, 244, 246, ...","[240, 239, 241, 238]"
215,332,4,0.754505,"[(215, False), (214, False), (216, False), (21...","[215, 214, 216, 213, 218, 217, 212, 219, 221, ...","[215, 214, 216, 213]"
314,332,4,0.754505,"[(314, False), (312, False), (313, False), (30...","[314, 312, 313, 308, 307, 309, 310, 305, 311, ...","[314, 312, 313, 308]"
143,332,4,0.754505,"[(143, False), (142, False), (144, False), (14...","[143, 142, 144, 141, 146, 145, 140, 147, 149, ...","[143, 142, 144, 141]"

In [8]:
# original results
pd.read_csv("original_results.csv")

,node,rho,sigma,q,ranks,reference,subgroup
0,46,9,3,0.320750,"[(46, np.False_), (np.int64(44), np.False_), (...","[46, np.int64(44), np.int64(47), np.int64(45),...","[46, np.int64(44), np.int64(47)]"
1,28,14,5,0.230508,"[(28, np.True_), (np.int64(27), np.False_), (n...","[28, np.int64(27), np.int64(26), np.int64(29),...","[28, np.int64(27), np.int64(26), np.int64(29),..."
2,35,13,5,0.228987,"[(35, np.True_), (np.int64(34), np.False_), (n...","[35, np.int64(34), np.int64(33), np.int64(36),...","[35, np.int64(34), np.int64(33), np.int64(36),..."
3,11,11,7,0.207201,"[(11, np.True_), (np.int64(12), np.False_), (n...","[11, np.int64(12), np.int64(8), np.int64(6), n...","[11, np.int64(12), np.int64(8), np.int64(6), n..."
4,253,22,13,0.206959,"[(253, np.False_), (np.int64(255), np.True_), ...","[253, np.int64(255), np.int64(254), np.int64(2...","[253, np.int64(255), np.int64(254), np.int64(2..."
5,268,5,3,0.206559,"[(268, np.True_), (np.int64(269), np.False_), ...","[268, np.int64(269), np.int64(267), np.int64(2...","[268, np.int64(269), np.int64(267)]"
6,167,5,3,0.206559,"[(167, np.True_), (np.int64(168), np.False_), ...","[167, np.int64(168), np.int64(166), np.int64(1...","[167, np.int64(168), np.int64(166)]"
7,300,19,11,0.192952,"[(300, np.True_), (np.int64(299), np.False_), ...","[300, np.int64(299), np.int64(301), np.int64(2...","[300, np.int64(299), np.int64(301), np.int64(2..."
8,180,5,4,0.178885,"[(180, np.False_), (np.int64(179), np.False_),...","[180, np.int64(179), np.int64(181), np.int64(1...","[180, np.int64(179), np.int64(181), np.int64(1..."
9,19,19,10,0.171823,"[(19, np.True_), (np.int64(20), np.False_), (n...","[19, np.int64(20), np.int64(14), np.int64(12),...","[19, np.int64(20), np.int64(14), np.int64(12),..."
10,149,19,10,0.171823,"[(149, np.True_), (np.int64(147), np.False_), ...","[149, np.int64(147), np.int64(150), np.int64(1...","[149, np.int64(147), np.int64(150), np.int64(1..."
11,282,25,10,0.164438,"[(282, np.True_), (np.int64(280), np.False_), ...","[282, np.int64(280), np.int64(283), np.int64(2...","[282, np.int64(280), np.int64(283), np.int64(2..."
12,145,12,7,0.163663,"[(145, np.True_), (np.int64(144), np.False_), ...","[145, np.int64(144), np.int64(146), np.int64(1...","[145, np.int64(144), np.int64(146), np.int64(1..."
13,132,23,10,0.157678,"[(132, np.True_), (np.int64(130), np.False_), ...","[132, np.int64(130), np.int64(133), np.int64(1...","[132, np.int64(130), np.int64(133), np.int64(1..."
14,260,11,6,0.156662,"[(260, np.True_), (np.int64(258), np.False_), ...","[260, np.int64(258), np.int64(259), np.int64(2...","[260, np.int64(258), np.int64(259), np.int64(2..."
15,39,11,6,0.156662,"[(39, np.True_), (np.int64(38), np.False_), (n...","[39, np.int64(38), np.int64(40), np.int64(37),...","[39, np.int64(38), np.int64(40), np.int64(37),..."
16,296,11,6,0.156662,"[(296, np.False_), (np.int64(297), np.True_), ...","[296, np.int64(297), np.int64(298), np.int64(2...","[296, np.int64(297), np.int64(298), np.int64(2..."
17,304,7,3,0.155870,"[(304, np.True_), (np.int64(303), np.False_), ...","[304, np.int64(303), np.int64(302), np.int64(3...","[304, np.int64(303), np.int64(302)]"
18,274,22,10,0.153227,"[(274, np.True_), (np.int64(272), np.False_), ...","[274, np.int64(272), np.int64(275), np.int64(2...","[274, np.int64(272), np.int64(275), np.int64(2..."
19,280,31,5,0.150280,"[(280, np.False_), (np.int64(282), np.True_), ...","[280, np.int64(282), np.int64(281), np.int64(2...","[280, np.int64(282), np.int64(281), np.int64(2..."